name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker Image
       
        run: docker build -t my-website:latest ./my_website

      - name: Test Docker Container
        run: |
          # تأكد إنّ اسم الـ image هو نفسه اللي عملنا له build فوق
          docker run -d -p 80:80 --name test-container my-website:latest
          sleep 5
          docker ps | grep test-container